### ISSUE TITLE
支持SRT

### ISSUE THREAD

**Issue by lio19** [q191201771/lalmax#3]
### 为什么

- 目前开源社区较流行的流媒体服务器都支持这个协议，做为能力补齐的一部分，我觉得我们也需要支持这个协议
- ffmpeg，OBS都能直接推拉流SRT流。说明SRT也是接受度较高的协议。对于用户来说，也是可以直接上手使用的一个协议
- 由于SRT相对于别的推拉流协议，功能做得相对完善需要开源社区的力量，这个也正好符合我们开lalmax的目标

基于以上的考虑，我觉得我们SRT的支持可以作为优先级较高的项目推进

@q191201771 @ZSC714725 你们觉得呢？

**Comment by q191201771** [comment]
看看这个：
https://github.com/q191201771/lalext/tree/master/srt

**Comment by ZSC714725** [comment]
lalext的srt功能只支持推流模式，srt拉流模式可以等后面回调接口开出来实现一下

**Comment by ZSC714725** [comment]
https://github.com/q191201771/lalmax/pull/6，srt拉流

**Comment by ZSC714725** [comment]
发现一个纯go实现的srt库，后续可以考虑使用该仓库：https://github.com/datarhei/gosrt

**Comment by ZSC714725** [comment]
目前mediamtx已经支持SRT，使用的是gosrt这个库，打算跟进

**Comment by ZSC714725** [comment]
https://github.com/q191201771/lalmax/pull/23
使用gosrt
