### ISSUE TITLE
国标禁用 panic

### ISSUE THREAD

**Issue by ixugo** [q191201771/lalmax#53]
<img width="349" alt="image" src="https://github.com/q191201771/lalmax/assets/59127546/8963fb06-dd97-4b92-a6b8-8103fd9033c9">

如上图所示，应该判断 国标对象是否为空。
<img width="239" alt="image" src="https://github.com/q191201771/lalmax/assets/59127546/4f608a74-c4f0-422f-836c-fdc10acda426">

**Comment by ZSC714725** [comment]
> <img alt="image" width="349" src="https://private-user-images.githubusercontent.com/59127546/307568709-8963fb06-dd97-4b92-a6b8-8103fd9033c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDc5MzQsIm5iZiI6MTcwOTAwNzYzNCwicGF0aCI6Ii81OTEyNzU0Ni8zMDc1Njg3MDktODk2M2ZiMDYtZGQ5Ny00YjkyLWE2YjgtODEwM2ZkOTAzM2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTJkYzIzNWIzNjliYTYxZDY4NTRhNmMzNGJiOTFhNGRkZjk1YjA3ZTRjMGFkOWU2NjUzMTcwZWU5MDNjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uJZWAQonEUNDNa_ouIZcch3Y5OhA39_W79H8xZNyvss">
> 如上图所示，应该判断 国标对象是否为空。 <img alt="image" width="239" src="https://private-user-images.githubusercontent.com/59127546/307568730-4f608a74-c4f0-422f-836c-fdc10acda426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDc5MzQsIm5iZiI6MTcwOTAwNzYzNCwicGF0aCI6Ii81OTEyNzU0Ni8zMDc1Njg3MzAtNGY2MDhhNzQtYzRmMC00MjJmLTgzNmMtZmRjMTBhY2RhNDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA0MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5Y2Q5MjA1ZjgzMzhhMTY1ZTZhYTc2ZWJiMzBhOWUzZjFlODhhYWYxNWM3MGI5M2RjMTA4ODAxYmE1NzA5YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEPw6iYCAljcAf8PGllpBMCzFvEN99OLiIrp6IrJk64">

update
