### ISSUE TITLE
统计 all_group 信息时，相关的订阅查不到，全部存在 hook 的 sync.map 里。

### ISSUE THREAD

**Issue by ixugo** [q191201771/lalmax#57]
统计 all_group 信息时，相关的订阅查不到，全部存在 hook 的 sync.map 里。

比如说 rtmp 推到 lal，采用 whep 播放，订阅信息存放在 hookSession 里，all_group 肯定查询不到。

有什么比较好的解决方案吗 ?

**Comment by joestarzxh** [comment]
需要lal中的接口封装到lalmax中，lalmax做lal的统一入口，有没有兴趣提供pr
